name: Demo Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test code
        run: npm run lint
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Intall Dependencies
        run: npm ci
      - name: Trigger build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output
        run: ls
      - name: deploy
        run: echo "Deploying..."
